-- Step 3: admin audit log for case changes.
-- Run this after 001 and 002.

begin;

create table if not exists public.admin_case_audit_logs (
  id bigint generated by default as identity primary key,
  case_id text not null,
  admin_user_id uuid not null,
  action text not null,
  patch jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_case_audit_logs_case_id_idx
  on public.admin_case_audit_logs (case_id, created_at desc);

create index if not exists admin_case_audit_logs_admin_user_id_idx
  on public.admin_case_audit_logs (admin_user_id, created_at desc);

alter table if exists public.admin_case_audit_logs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'admin_case_audit_logs'
      and policyname = 'admin_case_audit_logs_admin_all'
  ) then
    create policy admin_case_audit_logs_admin_all
      on public.admin_case_audit_logs
      for all
      using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
      with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
  end if;
end $$;

commit;
